### ISSUE TITLE
Test on linux

### ISSUE THREAD

**Issue by ogmkp** [JumpShot-Interactive/TeleScore#3]
Hi and thanks for this project.

I tried from a Linux Debian 11, I installed the requirements but I get the following message when running main.py:

> $ python3 src/main.py 
Traceback (most recent call last):
  File "/TeleScore-Beta/src/main.py", line 16, in <module>
    from window.mainwindow import MainWindow
  File "/TeleScore-Beta/src/window/mainwindow.py", line 10, in <module>
    from window.editor import Editor
  File "/TeleScore-Beta/src/window/editor.py", line 326
    match evt.key():
               ^
SyntaxError: invalid syntax
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/TeleScore-Beta/src/main.py", line 18, in <module>
    import src
ModuleNotFoundError: No module named 'src'

How to resolve this ?
Thanks.

**Comment by riscyseven** [comment]
Hi, 
In the main.py, there is a variable named DEBUG.
Can you try setting that variable to True?

**Comment by ogmkp** [comment]
Yes, I have this:

>$ python3 src/main.py 
Traceback (most recent call last):
  File "/TeleScore-Beta/src/main.py", line 24, in <module>
    from window.mainwindow import MainWindow
  File "/TeleScore-Beta/src/window/mainwindow.py", line 10, in <module>
    from window.editor import Editor
  File "/TeleScore-Beta/src/window/editor.py", line 326
    match evt.key():
          ^
SyntaxError: invalid syntax

**Comment by riscyseven** [comment]
Do you have Python version greater than 3.10?

**Comment by ogmkp** [comment]
Oops, Python 3.9.2, sorry my fault, there no 3.10 in Debian 11 repository.

**Comment by riscyseven** [comment]
Let me know if you make any progress
