### ISSUE TITLE
can't start app

### ISSUE THREAD

**Issue by hemna** [JumpShot-Interactive/TeleScore#8]
created venv, sourced venv
git cloned repo
installed requirements

```
└─> pip install -r requirements.txt
Collecting PyQt6==6.4.2
  Downloading PyQt6-6.4.2-cp37-abi3-macosx_10_14_universal2.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 9.5 MB/s eta 0:00:00
Collecting requests==2.28.2
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting pynput==1.7.6
  Downloading pynput-1.7.6-py2.py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.2/89.2 kB 3.0 MB/s eta 0:00:00
Collecting cx-Freeze==6.14.2
  Downloading cx_Freeze-6.14.2-cp310-cp310-macosx_10_9_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 7.1 MB/s eta 0:00:00
Collecting PyQt6-Qt6>=6.4.0
  Downloading PyQt6_Qt6-6.4.3-py3-none-macosx_10_14_x86_64.whl (49.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 MB 8.9 MB/s eta 0:00:00
Collecting PyQt6-sip<14,>=13.4
  Downloading PyQt6_sip-13.4.1-cp310-cp310-macosx_10_9_universal2.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 5.2 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-macosx_10_9_x86_64.whl (124 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyobjc-framework-Quartz>=8.0
  Downloading pyobjc_framework_Quartz-9.0.1-cp310-cp310-macosx_10_9_universal2.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 3.9 MB/s eta 0:00:00
Collecting pyobjc-framework-ApplicationServices>=8.0
  Downloading pyobjc_framework_ApplicationServices-9.0.1-cp310-cp310-macosx_10_9_universal2.whl (32 kB)
Collecting setuptools<67,>=61.2
  Using cached setuptools-66.1.1-py3-none-any.whl (1.3 MB)
Collecting pyobjc-core>=9.0.1
  Downloading pyobjc_core-9.0.1-cp310-cp310-macosx_10_9_universal2.whl (738 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.6/738.6 kB 4.3 MB/s eta 0:00:00
Collecting pyobjc-framework-Cocoa>=9.0.1
  Downloading pyobjc_framework_Cocoa-9.0.1-cp310-cp310-macosx_10_9_universal2.whl (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.5/388.5 kB 7.5 MB/s eta 0:00:00
Installing collected packages: PyQt6-Qt6, urllib3, six, setuptools, PyQt6-sip, pyobjc-core, idna, charset-normalizer, certifi, requests, PyQt6, pyobjc-framework-Cocoa, cx-Freeze, pyobjc-framework-Quartz, pyobjc-framework-ApplicationServices, pynput
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.4.0
    Uninstalling setuptools-67.4.0:
      Successfully uninstalled setuptools-67.4.0
Successfully installed PyQt6-6.4.2 PyQt6-Qt6-6.4.3 PyQt6-sip-13.4.1 certifi-2022.12.7 charset-normalizer-3.1.0 cx-Freeze-6.14.2 idna-3.4 pynput-1.7.6 pyobjc-core-9.0.1 pyobjc-framework-ApplicationServices-9.0.1 pyobjc-framework-Cocoa-9.0.1 pyobjc-framework-Quartz-9.0.1 requests-2.28.2 setuptools-66.1.1 six-1.16.0 urllib3-1.26.15
╭─TeleScore on  main via 🐍 v3.10.10 (.venv) took 26s ❯
```

```
╭─TeleScore on  main via 🐍 v3.10.10 (.venv) ❯
└─> ll
drwxr-xr-x i530566 staff 320 B  Mon Mar 27 14:13:29 2023  .git/
drwxr-xr-x i530566 staff 128 B  Mon Mar 27 14:13:29 2023  .github/
.rw-r--r-- i530566 staff 801 B  Mon Mar 27 14:13:29 2023  .gitignore
drwxr-xr-x i530566 staff 128 B  Mon Mar 27 14:13:29 2023  extra/
.rw-r--r-- i530566 staff  34 KB Mon Mar 27 14:13:29 2023  LICENSE
.rw-r--r-- i530566 staff 502 KB Mon Mar 27 14:13:29 2023  logo.png
drwxr-xr-x i530566 staff  96 B  Mon Mar 27 14:13:29 2023  plugin/
.rw-r--r-- i530566 staff 2.7 KB Mon Mar 27 14:13:29 2023  README.md
.rw-r--r-- i530566 staff  61 B  Mon Mar 27 14:13:29 2023  requirements.txt
.rw-r--r-- i530566 staff 1.3 KB Mon Mar 27 14:13:29 2023  setup.py
.rw-r--r-- i530566 staff 233 KB Mon Mar 27 14:13:29 2023  showcase0.png
.rw-r--r-- i530566 staff 705 KB Mon Mar 27 14:13:29 2023  showcase1.gif
.rw-r--r-- i530566 staff 921 KB Mon Mar 27 14:13:29 2023  showcase2.gif
.rw-r--r-- i530566 staff 185 KB Mon Mar 27 14:13:29 2023  showcase3.gif
drwxr-xr-x i530566 staff 576 B  Mon Mar 27 14:13:29 2023  src/
╭─TeleScore on  main via 🐍 v3.10.10 (.venv) ❯
└─> python src/main.py
Traceback (most recent call last):
  File "/Users/i530566/Desktop/Soccer games/scoring/TeleScore/src/main.py", line 14, in <module>
    import src
ModuleNotFoundError: No module named 'src'
```

```
╭─TeleScore on  main via 🐍 v3.10.10 (.venv) ❯
└─> python --version
Python 3.10.10
```

**Comment by hemna** [comment]
Also tried,

```
╭─TeleScore on  main via 🐍 v3.10.10 (.venv) took 29s ❯
└─> pip install -e .
Obtaining file:///Users/i530566/Desktop/Soccer%20games/scoring/TeleScore
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/i530566/Desktop/Soccer games/scoring/TeleScore/setup.py", line 44, in <module>
          options={"build_exe": build_exe_options},
      NameError: name 'build_exe_options' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by riscyseven** [comment]
Hi,

In the main python file (main.py). There is a variable called DEBUG at the first few lines of the code (This will be refractored for sure in the near future) is it set to True? 

Thanks,
